# vim: ft=tmux
set -g status-interval 1
set -g status on
set -sg escape-time 0
set -g status-justify centre

set -g base-index 1
setw -g pane-base-index 1

set -g status-left-length "100"
set -g status-right-length "100"
set-option -g status-style bg=default

set -g message-style "fg=#C1C0D4,bg=default"
set -g message-command-style "fg=#C1C0D4,bg=default"

set -g pane-border-style "fg=#191724"
set -g pane-active-border-style "fg=#C1C0D4"

set -g status-left "#[fg=#757581,bg=default] #S"
set -g status-right "#[fg=#757581,bg=default] %l:%M %p"


setw -g window-status-separator "    "
setw -g window-status-style "NONE,fg=#757581,bg=default"
setw -g window-status-format '#I:#{b:pane_current_command}'
setw -g window-status-current-format '#[fg=#ACA1CF]#I:#{b:pane_current_command}*'
